# Configuration for Alacritty terminal emulator

# shell:
#   program: /usr/bin/env
#   args:
#     - zsh

window:
  # window padding (change requires restart)
  padding:
    x: 2
    y: 2
  # spread additional padding evenly around the terminal content
  dynamic_padding: true
  # window decoarations
  # - full: borders and title bar
  # - none: neither borders nor title bar
  # - (macos) transparent: title bar, transparent background, and title bar buttons
  # - (macos) buttonless: title bar transparent background, but no title bar buttons
  decorations: buttonless
  # dynamically set the window title
  dynamic_title: true
  # Startup mode
  # - Windowed
  # - Maximized
  # - Fullscreen
  # - SimpleFullscreen (macos only)
  startup_mode: Windowed

scrolling:
  history: 10000
  multiplier: 3

# Font settings
font:
  normal:
    family: Iosevka Nerd Font
    style: Regular
  bold:
    family: Iosevka Nerd Font
    style: Bold

  italic:
    family: Iosevka Nerd Font
    style:  Italic
  # point size
  size: 14.0
  # extra space around each character.
  # offset.y can be thought of as modifying the line spacing
  # offset.x can be thought of as modifying the letter spacing
  offset:
    x: 0
    y: 6
  glyph_offset:
    x: 0
    y: 4
  # draw bold text with bright color variants
  draw_bold_text_with_bright_colors: true
mouse:
  # hide the cursor when typing
  hide_when_typing: true
  # save selected text to system clipboard
  save_to_clipboard: true
cursor:
  # Cursor style
  # - â–‡ Block
  # - _ Underline
  # - | Beam
  style: Beam
  # render the cursor as a hollow box when window is not focused
  unfocused_hollow: true

# automatically reload config upon change
live_config_reload: true

# set the backgeround opacity
window_opacity: 0.8

colors:
  # Default colors
  primary:
    background: '0x282a36'
    foreground: '0xf8f8f2'
 
  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xbd93f9'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xbbbbbb'
 
  # Bright colors
  bright:
    black:   '0x555555'
    red:     '0xff5555'
    green:   '0x50fa7b'
    yellow:  '0xf1fa8c'
    blue:    '0xcaa9fa'
    magenta: '0xff79c6'
    cyan:    '0x8be9fd'
    white:   '0xffffff'
